### ISSUE TITLE
Advice: Making multiple GRAPH calls from the same solution

### ISSUE THREAD

**Issue by LiamDick** [OfficeDev/Office-Addin-TaskPane-SSO-JS#25]
Hi,

I have been working through the tutorials and have reached a dead end when it comes to expanding the solution to make multiple calls.

I followed the following tutorials to produce the add-in and connect to Graph and edit it.
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart-customize

I have not been able to find a way to take the SSO example set up through Yeoman and expand it to make multiple different calls as I cannot understand how all the parts of the Office-Addin-SSO fit together and how someone would customise to make multiple calls from the application or to make a post request with a body.

Any assistance would be appreciated.

**Comment by millerds** [comment]
This was a limitation of the project produced by 'yo office'. Yesterday I published a significant change to the SSO templates that puts the abstracted "middler tier" was in office-addin-sso package directly in the template instead. If you create a new project using 'yo office' you'll see a "middle-tier" folder where you can customize the serverside calls to graph to do whatever you want and change what the taskpane client is able to call in order to get things done.
